# Generated by Django 2.1.7 on 2019-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name_cn',
            field=models.CharField(max_length=20, null=True, verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
