# Generated by Django 2.1.7 on 2019-05-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20190506_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pair',
            field=models.CharField(max_length=20, null=True, verbose_name='test2'),
        ),
        migrations.AddField(
            model_name='test',
            name='rate',
            field=models.CharField(max_length=20, null=True, verbose_name='test1'),
        ),
    ]
