# Generated by Django 2.1.7 on 2019-05-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20190507_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='now_time',
            field=models.CharField(max_length=20, null=True, verbose_name='test2'),
        ),
    ]
