# Generated by Django 2.1.7 on 2019-05-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_test_now_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer_test',
            },
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='name_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='now_time',
            field=models.CharField(max_length=200, null=True, verbose_name='test2'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pair',
            field=models.CharField(max_length=200, null=True, verbose_name='test2'),
        ),
        migrations.AlterField(
            model_name='test',
            name='rate',
            field=models.CharField(max_length=200, null=True, verbose_name='test1'),
        ),
    ]
