# Generated by Django 2.1.7 on 2019-05-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20190514_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='test'),
        ),
        migrations.AddField(
            model_name='customer',
            name='now_time',
            field=models.CharField(max_length=200, null=True, verbose_name='test2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pair',
            field=models.CharField(max_length=200, null=True, verbose_name='test2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rate',
            field=models.CharField(max_length=200, null=True, verbose_name='test1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='name_test',
        ),
    ]
