# Generated by Django 2.1.7 on 2019-05-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_auto_20190514_0624'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='2019-05-14',
        ),
    ]
