# Generated by Django 2.1.7 on 2019-05-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20190514_0625'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='2019-05-15',
        ),
    ]
