# Generated by Django 2.1.7 on 2019-05-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_auto_20190514_1040'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='2019_05_15',
        ),
    ]
